// <auto-generated />
using System;
using Infrastructure.DBs;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20251202084747_register id2")]
    partial class registerid2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Asset", b =>
                {
                    b.Property<Guid>("AssetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AssetId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("Domain.Entities.AssetConfiguration", b =>
                {
                    b.Property<Guid>("AssetConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SignaTypeID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AssetConfigId");

                    b.HasIndex("SignaTypeID");

                    b.HasIndex("AssetId", "SignaTypeID")
                        .IsUnique();

                    b.ToTable("AssetConfigurations");
                });

            modelBuilder.Entity("Domain.Entities.SignalData", b =>
                {
                    b.Property<long>("SignalDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SignalDataId"));

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("AvgValue")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("float");

                    b.Property<DateTime>("BucketStartUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DevicePortId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("MaxValue")
                        .HasColumnType("float");

                    b.Property<double?>("MinValue")
                        .HasColumnType("float");

                    b.Property<int?>("RegisterAddress")
                        .HasColumnType("int");

                    b.Property<string>("SignalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("SignalTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SignalUnit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Sum")
                        .HasColumnType("float");

                    b.HasKey("SignalDataId");

                    b.HasIndex("AssetId", "BucketStartUtc")
                        .HasDatabaseName("IX_SignalData_Asset_Bucket");

                    b.HasIndex("SignalTypeId", "BucketStartUtc")
                        .HasDatabaseName("IX_SignalData_SignalType_Bucket");

                    b.HasIndex("DeviceId", "DevicePortId", "BucketStartUtc")
                        .HasDatabaseName("IX_SignalData_Device_Bucket");

                    b.HasIndex("AssetId", "SignalTypeId", "DeviceId", "DevicePortId", "BucketStartUtc")
                        .IsUnique()
                        .HasDatabaseName("UX_SignalData_BucketKey");

                    b.ToTable("SignalData");
                });

            modelBuilder.Entity("Domain.Entities.SignalTypes", b =>
                {
                    b.Property<Guid>("SignalTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DefaultRegisterAdress")
                        .HasColumnType("int");

                    b.Property<string>("SignalName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SignalUnit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SignalTypeID");

                    b.ToTable("SignalTypes");
                });

            modelBuilder.Entity("MappingService.Domain.Entities.AssetSignalDeviceMapping", b =>
                {
                    b.Property<Guid>("MappingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DevicePortId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RegisterAdress")
                        .HasColumnType("int");

                    b.Property<string>("SignalName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SignalTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SignalUnit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("registerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MappingId");

                    b.HasIndex("AssetId", "SignalTypeId")
                        .HasDatabaseName("IX_Mapping_Asset_Signal");

                    b.HasIndex("DeviceId", "DevicePortId")
                        .HasDatabaseName("IX_Mapping_Device_Port");

                    b.ToTable("MappingTable");
                });

            modelBuilder.Entity("Domain.Entities.Asset", b =>
                {
                    b.HasOne("Domain.Entities.Asset", null)
                        .WithMany("Childrens")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Domain.Entities.AssetConfiguration", b =>
                {
                    b.HasOne("Domain.Entities.Asset", "Asset")
                        .WithMany("AssetConfigurations")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.SignalTypes", "SignalType")
                        .WithMany("AssetConfigurations")
                        .HasForeignKey("SignaTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("SignalType");
                });

            modelBuilder.Entity("Domain.Entities.Asset", b =>
                {
                    b.Navigation("AssetConfigurations");

                    b.Navigation("Childrens");
                });

            modelBuilder.Entity("Domain.Entities.SignalTypes", b =>
                {
                    b.Navigation("AssetConfigurations");
                });
#pragma warning restore 612, 618
        }
    }
}
