// <auto-generated />
using System;
using Infrastructure.DBs;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20251120061718_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Asset", b =>
                {
                    b.Property<Guid>("AssetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AssetId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("Domain.Entities.AssetConfiguration", b =>
                {
                    b.Property<Guid>("AssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SignaTypeID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssetConfigId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AssetId", "SignaTypeID");

                    b.HasIndex("SignaTypeID");

                    b.HasIndex("AssetId", "SignaTypeID")
                        .IsUnique();

                    b.ToTable("AssetConfigurations");
                });

            modelBuilder.Entity("Domain.Entities.SignalTypes", b =>
                {
                    b.Property<Guid>("SignalTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SignalName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SignalUnit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SignalTypeID");

                    b.ToTable("SignalTypes");
                });

            modelBuilder.Entity("Domain.Entities.Asset", b =>
                {
                    b.HasOne("Domain.Entities.Asset", null)
                        .WithMany("Childrens")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Domain.Entities.AssetConfiguration", b =>
                {
                    b.HasOne("Domain.Entities.Asset", "Asset")
                        .WithMany("AssetConfigurations")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.SignalTypes", "SignalType")
                        .WithMany("AssetConfigurations")
                        .HasForeignKey("SignaTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("SignalType");
                });

            modelBuilder.Entity("Domain.Entities.Asset", b =>
                {
                    b.Navigation("AssetConfigurations");

                    b.Navigation("Childrens");
                });

            modelBuilder.Entity("Domain.Entities.SignalTypes", b =>
                {
                    b.Navigation("AssetConfigurations");
                });
#pragma warning restore 612, 618
        }
    }
}
